import React from "react";

import {
Search,
FileText,
Printer,
Download,
Eye
} from "lucide-react";


import "../css/ReportsReceipts.css";


const ReportsReceipts=()=>{


const reports=[

{
id:1,
name:"Monthly Sales Report",
date:"2026-07-28",
generated:"Admin"
},

{
id:2,
name:"Product Issue Receipt",
date:"2026-07-25",
generated:"Manager"
}


];


return(

<div className="report-page">


<h1>
Reports / Receipts
</h1>

<p>
View transactions, records and generated receipts.
</p>



<div className="report-tools">


<div className="search-box">

<Search size={18}/>

<input placeholder="Search reports..."/>

</div>


<button>
<FileText size={18}/>
Generate Report
</button>


</div>



<div className="report-card">


<table>


<thead>

<tr>

<th>ID</th>
<th>Report Name</th>
<th>Date</th>
<th>Generated By</th>
<th>Action</th>

</tr>

</thead>


<tbody>


{
reports.map(r=>(


<tr key={r.id}>

<td>{r.id}</td>

<td>
<FileText size={18}/>
{r.name}
</td>


<td>{r.date}</td>

<td>{r.generated}</td>


<td>


<button>
<Eye size={17}/>
</button>


<button>
<Printer size={17}/>
</button>


<button>
<Download size={17}/>
</button>


</td>


</tr>


))
}



</tbody>


</table>


</div>


</div>

)

}


export default ReportsReceipts;